CORE ?= esp32
BOARD ?= ttgo-t7-v14-mini32

UploadSpeed := 921600
SERIAL_PORT ?= /dev/ttyACM0
TERMINAL_SPEED := 19200
TERMINAL_EXTRA_FLAGS := -C serialout.txt
#CPPFLAGS := -DTERMINAL_SPEED=$(TERMINAL_SPEED) -DNO_STORAGE -DUSE_HOST_DISPLAY -DUSE_HOST_KBD -DDEBUGGING=0x03
CPPFLAGS := -DTERMINAL_SPEED=$(TERMINAL_SPEED) -DNO_STORAGE -DUSE_HOST_DISPLAY -DUSE_HOST_KBD
LIBRARIES = SimpleTimer

include $(CORE).mk
